### ISSUE TITLE
[Bug] `calibre site create-deploy` failing on syntax error

### ISSUE THREAD

**Issue by omgaz** [calibreapp/cli#741]
### Describe the bug

Hiya 👋🏻 

We're getting a failure on the latest npm release of the calibre cli, v5.2.0 with the graphql-request module that was upgraded last week via https://github.com/calibreapp/cli/pull/719

```
import { OperationTypeNode } from 'graphql';
         ^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'OperationTypeNode' not found. The requested module 'graphql' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'graphql';
const { OperationTypeNode } = pkg;
```

Can reproduce locally using:

```shell
npm install calibre@5.2.0 --save
npx calibre site create-deploy
```

We're using NodeJS v18.16.1 with NPM v9.5.1, locally and in GitHub actions Ubuntu runners.

```
Run npm install calibre --save && npx calibre site create-deploy --site=$CALIBRE_SITE_SLUG --revision=$GITHUB_SHA --repository https://github.com/$GITHUB_REPOSITORY
```

Rolling back to `npm install calibre@5.1.3 --save` works as a work-around.

Thanks,
Gaz

### CLI Installation Method

npm

### CLI Version

5.2.0

### What’s your operating system?

Mac

### How To Reproduce

Locally on a mac:
```
npm install calibre@5.2.0 --save
npx calibre site create-deploy
```

in Github actions as:

```
name: Calibre

on:
  workflow_call:
    secrets:
      CALIBRE_API_TOKEN:
        required: true
      CALIBRE_SITE_SLUG:
        required: true

permissions:
  contents: read

jobs:
  calibre:
    name: Calibre
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Calibre Deploy
        run: |
          npm install calibre --save && npx calibre site create-deploy --site=$CALIBRE_SITE_SLUG --revision=$GITHUB_SHA --repository https://github.com/$GITHUB_REPOSITORY
        env:
          CALIBRE_API_TOKEN: ${{ secrets.CALIBRE_API_TOKEN }}
          CALIBRE_SITE_SLUG: ${{ secrets.CALIBRE_SITE_SLUG }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.event.repository.name }}
```

### Relevant Log Output

```shell
import { OperationTypeNode } from 'graphql';
         ^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'OperationTypeNode' not found. The requested module 'graphql' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'graphql';
const { OperationTypeNode } = pkg;
```

### Screenshots

<img width="1122" alt="Screenshot 2024-09-04 at 14 37 04" src="https://github.com/user-attachments/assets/3a61845c-cb17-4442-a0e8-2b926d34944f">

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct
